Sdk browser
resin-io/resin-token pull request #26
Opened 2016-10-09 21:49 UTC by emirotin

This PR follows the same scheme as the previous one. It's currently not squashed, will do before merging.

Once again I don't know how to properly tweak jsdoc. It mixes inner and static methods. Can you help?

2016-10-13 22:12 UTC, jviotti commented
Sorry for the delay, taking a look now!

2016-10-13 22:26 UTC, jviotti commented
@emirotin This is getting a bit tricky. If you like, lets merge and publish so it doesn't block you, and you can open an issue for it (and assign me), and I'll do it once I return from vacations!

2016-10-13 22:32 UTC, emirotin commented
Yeah no worries I know you're on holiday.
I obviously has tried figuring it out myself, but the magic JSDoc tries to apply plays against it here.

If you're fine with that I can do it, not super happy to publish the module with slightly broken docs, but at least the snippets should be explanatory.

2016-10-13 22:59 UTC, Page- requested changes

2016-10-13 22:59 UTC, Page- commented on lib/token.coffee
> +			try
This would be better as:
```coffee
Promise.try ->
	jwtDecode(token.trim())
.catch ->
	throw new errors.ResinMalformedToken(token)
```

2016-10-14 05:17 UTC, emirotin commented on lib/token.coffee
> +			try
Yeah, I just replaced the custom logic here, but for sure that can be improved.

2016-10-28 19:26 UTC, Page- approved these changes

2016-11-18 20:48 UTC, emirotin commented
I've moved the only method documentation (the factory itself) to the static preamble in the readme template and solved my problems. Merging now and will apply the same fix to the rest of the modules.

2016-11-18 20:48 UTC, merged