29 expired token
resin-io/resin-token pull request #30
Opened 2017-04-20 17:57 UTC by emirotin

Fixes #29

2017-04-20 23:46 UTC, Page- requested changes

2017-04-20 23:46 UTC, Page- commented on build/token.js
>        if (!isValid) {
Can you add the `header: true` bit to the gulpfile so this file's diff gets dropped please

2017-04-20 23:46 UTC, Page- commented on CHANGELOG.md
> +- The token expiration is not checked in `set` and the expired tokens are rejected
I think `not` is meant to be `now`?

2017-04-21 20:17 UTC, emirotin commented
Ping on this

2017-04-21 21:08 UTC, Page- approved these changes

2017-04-22 11:23 UTC, pimterry approved these changes

2017-04-23 20:31 UTC, merged