Typescript
resin-io/resin-token pull request #32
Opened 2017-08-30 14:18 UTC by emirotin

2017-08-31 09:47 UTC, pimterry requested changes

2017-08-31 09:47 UTC, pimterry commented on README.md
> -
This removes all the docs, we should definitely keep those.

2017-08-31 09:47 UTC, pimterry commented on lib/token.ts
> + */
We can drop this

2017-08-31 09:47 UTC, pimterry commented on lib/token.ts
> +	 * In this context, "data" refers to the information encoded in the token.
I think it'd be useful to note that this resolves to undefined if there is no token available.

2017-08-31 09:47 UTC, pimterry commented on lib/token.ts
> +	 * It also resolved to undefined if the property name is invalid.
Also resolves to undefined if there is no token available.

2017-08-31 09:47 UTC, pimterry commented on lib/token.ts
> +	 * 	console.log(parsedToken)
All these code examples are still coffeescript

2017-08-31 11:08 UTC, pimterry commented
Bonus point: now that we're sure this `@resin-io/types-*` approach is actually practical, we should raise it in a process call to check everybody else is happy with it, add it to the TypeScript guidelines, and bring it up on a monday call, so everybody else starts doing it too.

2017-08-31 14:00 UTC, emirotin commented on lib/token.ts
> + */
Missed in this file

2017-08-31 14:01 UTC, emirotin commented on README.md
> -
Hmm, of course we should, I wonder what has happened.

2017-08-31 14:05 UTC, emirotin commented on README.md
> -
Probably related to conversion to a class, will have to tinker with JSDoc a bit

2017-08-31 14:06 UTC, emirotin commented
@pimterry do you remember if we had AppVeyor for this repo? We don't have it now at least

2017-08-31 20:26 UTC, emirotin commented on lib/token.ts
> +	 * It also resolved to undefined if the property name is invalid.
Actually it's said in the first line

2017-08-31 20:30 UTC, emirotin commented
@pimterry please re-review

2017-09-01 05:03 UTC, pimterry approved these changes
Yep, needs squashing too, but otherwise looks great to me. Sorry, I have no idea if we used to have appveyor...

2017-09-01 06:50 UTC, emirotin commented
I'm pretty sure we had because we have the config file for it. I've asked Apo to switch it back on

2017-09-01 14:16 UTC, merged